// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts("127.0.0.1:8081"), server.WithExitWaitTime(0*time.Second))

	register(h)
	h.Spin()
}
