// Code generated by hertz generator.

package Account

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __uthmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
