// Code generated by hertz generator.

package account

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	account "user/setting/biz/model/sys/account"
)

// AuthMethod .
// @router /auth [POST]
func AuthMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req account.AuthReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(account.AuthResp)

	c.JSON(200, resp)
}
